services:
  eyes-face-follow:
    build: .
    network_mode: host
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - video
    devices:
      - /dev/dri
      - /dev/dri/renderD128
    environment:
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
      - SDL_VIDEODRIVER=wayland
      - PYOPENGL_PLATFORM=egl
      - HOME=/tmp
      - ROS_LOG_DIR=/tmp/ros/log
    volumes:
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
