services:
  eyes-face-follow:
    build: .
    restart: unless-stopped
    network_mode: host
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - video
    devices:
      - /dev/dri
      - /dev/dri/renderD128
    environment:
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
      - SDL_VIDEODRIVER=wayland
      - PYOPENGL_PLATFORM=egl
      - HOME=/tmp
      - ROS_LOG_DIR=/tmp/ros/log
      - USE_FACE_TOPIC=1
    volumes:
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}

  camera:
    container_name: ros-camera-eyes-facetrack
    build:
      context: .
      dockerfile: Dockerfile.camera
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/bus/usb
    environment:
      - OAKD_FACE_ENABLED=1
      - OAKD_FACE_CONFIDENCE=0.6
